apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "akv-sync-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: akv-sync-exporter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: akv-sync-exporter
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
