clusterName: ""

image:
  repository: acrplatformprod.azurecr.io/platform/controller-scaler
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  name: controller-scaler

argocdNamespace: argocd
pollIntervalSeconds: 5
