apiVersion: v1
kind: ConfigMap
metadata:
  name: mgmt-leader-status
  namespace: kube-system
  labels:
    app.kubernetes.io/name: mgmt-leader-lease
data:
  clusterName: {{ .Values.clusterName | quote }}
  holderIdentity: {{ .Values.clusterName | quote }}
  leadershipStatus: standby
  leaseID: ""
  preferredCluster: ""
  lastObservedAt: ""
  lastRenewedAt: ""

