apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: kube-system
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.clientId | quote }}
  labels:
    app.kubernetes.io/name: mgmt-leader-lease
    app.kubernetes.io/component: controller

