apiVersion: v1
kind: Service
metadata:
  name: mgmt-leader-lease-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: mgmt-leader-lease
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port | quote }}
spec:
  selector:
    app.kubernetes.io/name: mgmt-leader-lease
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics

